baseURL = 'https://modelpack.org/'
languageCode = 'en-us'
title = 'ModelPack - CNCF AI Model Packaging Standard'

[params]
  description = 'CNCF ModelPack is a vendor-neutral, open source specification standard to package, distribute and run AI models in cloud native environments'
  keywords = 'ModelPack, CNCF, AI, ML, OCI, Kubernetes, Cloud Native, Model Registry'



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
